# Generated by Django 4.2.20 on 2025-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, default='uploads/userprofile/default.jpeg', null=True, upload_to='uploads/userprofile'),
        ),
    ]
